name: Automated Tests (mitigations)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install playwright test runner
        run: |
          npm init -y
          npm install --no-audit --no-fund --save-dev @playwright/test
          npx playwright install --with-deps

      - name: Start static server
        run: |
          python3 -m http.server 8080 &>> server.log &
          echo "Started static server"
          sleep 2
          curl -f http://127.0.0.1:8080/ || echo "Warning: Server may not be ready"

      - name: Run Playwright tests and save JSON report
        run: |
          npx playwright test playwright-tests/test-runner.spec.js --reporter=json > test-results.json || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            server.log
            test-results.json
            test-results.png
            test-failure-debug.png
